spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/mingle_mate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/mingle_mate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    user: root
    password: password!23
---
server:
  port: 8000
  servlet:
    context-path: /api


jwt:
  secret: 865ca9043e48e5652309c62c46c9fe59e93588c43511c769b5b0415e2839cede7c95ea7ef0df8f0cf7c909867e665f84dc5ee1a468a59651fbee16991fd18be3

imp:
  restApiKey: 6704822164751663
  restApiSecretKey: wLkgfDVUuebAQW9IPJBUT2s6i7uKdPuSg6sUf5mp7hNYn8je4nwIK5XBfymXrTdhq5xkEPbeLhO3iOhl